import type {Metadata} from "next";
import "@/styles/global.scss";
import React from "react";
import SiteHeader from "@/component/site-header";
import {AntdRegistry} from "@ant-design/nextjs-registry";
import {Layout} from "antd";
import {Content} from "antd/lib/layout/layout";

export const metadata: Metadata = {
  title: "HAPPLOG",
  description: "Generated by create next app",
};
export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {

  const LayoutStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    maxWidth: 1280,
    backgroundColor: 'white',
    padding: '0 1.6rem',
  }

  const ContentStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    padding: '2rem 0',
  }

  return (
    <html lang="en">
    <head>
      <meta name="google-adsense-account" content="ca-pub-2570618898847074"/>
      <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-2570618898847074"
              crossOrigin="anonymous"></script>
    </head>
    <body>
    <AntdRegistry>
      <Layout style={LayoutStyle}>
      <SiteHeader/>
        <Content style={ContentStyle}>
          {children}
        </Content>
      </Layout>
    </AntdRegistry>
    </body>
    </html>
  );
}
